CREATE TABLE users(
	ID VARCHAR(255),
	NAME VARCHAR(255),
	ACCOUNT VARCHAR(255),
	PASSWORD VARCHAR(255)
);
ALTER TABLE users ADD PRIMARY KEY (ID);

INSERT INTO users(ID, NAME, ACCOUNT, PASSWORD) 
VALUE ('001','管理员','admin','password');